env:
  browser: yes
  commonjs: yes
  es6: yes
extends: 'eslint:recommended'
globals:
  Phaser: no
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
